id: P005639
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS66361
  title: བོང་སྟག་ཇ་སྐོར་གྱི་ཁྱིམ་རྒྱུད་ལོ་རྒྱུས་མུ་ཏིག་དཀར་པོའི་མཛོད
  author: ''
  volumes:
    5024db8d188349a7945f11c1b93a4a48:
      image_group_id: I1GS66365
      title: ''
      volume_number: 1
      total_pages: 181
