id: I42448222
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T02:47:32+00:00'
last_modified: '2022-06-08T05:28:59.086996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS66361
  title: བོང་སྟག་ཇ་སྐོར་གྱི་ཁྱིམ་རྒྱུད་ལོ་རྒྱུས་མུ་ཏིག་དཀར་པོའི་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    464F:
      image_group_id: I1GS66365
      title: ''
      total_pages: 181
      order: 1
      base_file: 464F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
